Python3 migration of move_group_python_interface_tutorial
ros-planning/moveit_tutorials pull request #536
Opened 2020-10-03 19:31 UTC by tylerjw

### Description

This makes the move_group_python_interface_tutorial both python2 and python3 compatible.  This is needed to run this tutorial on Noetic.

2020-10-04 10:02 UTC, rhaschke requested changes
Thanks for starting this. There are other not yet python3 compliant python files though. Please handle them all:
doc/collision_environments/scripts/collision_scene_example.py
_scripts/tutorialformatter.py

2020-10-04 19:55 UTC, tylerjw commented on doc/move_group_python_interface/scripts/move_group_python_interface_tutorial.py
> +from builtins import input
done

2020-10-04 19:55 UTC, tylerjw commented on doc/move_group_python_interface/scripts/move_group_python_interface_tutorial.py
> +    print("============ Planning frame: %s" % planning_frame)
done

2020-10-04 20:03 UTC, tylerjw commented
> Thanks for starting this. There are other not yet python3 compliant python files though. Please handle them all:
> doc/collision_environments/scripts/collision_scene_example.py
> _scripts/tutorialformatter.py

@rhaschke I updated this to include changes for collision_scene_example.py but was not able to find anything wrong with tutorialformatter.py.  I also don't understand how tutorialformatter.py is used so I wasn't able to test it outside of just calling it with python3 (which runs without error and produces no output).

2020-10-06 06:07 UTC, rhaschke commented
> I was not able to find anything wrong with tutorialformatter.py.

Sorry for the noise. I was looking at an older version of the file. Michael already fixed some stuff a while ago (#410).

> I also don't understand how tutorialformatter.py is used so I wasn't able to test it outside of just calling it with python3

It's used as a plugin to sphinx, generating the docs:
https://github.com/ros-planning/moveit_tutorials/blob/f0ac33f91603d7bffa8592d9a9b4943cec7eedea/conf.py#L5-L6

2020-10-06 06:08 UTC, rhaschke approved these changes

2020-10-06 06:08 UTC, merged